---
- hosts: all
  tasks:
  - name: Uninstall HTOP
    apt:
     pkg: htop
     state: absent
    become: true
  - name: Uninstall MariaDB
    apt:
     name: mariadb-server
     state: absent
    become: true
