- name: Ping Server
  hosts: all
  become: yes

  tasks:

  - name: Task-Ping
    ping:

  - name: Install Web-Server
    apt: 
     pkg: apache2
     state: present

  - name: copy file
    copy:
     src: ./file1.txt
     dest: /home/
     mode: 0777 
